name: Drone Network CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create venv
        run: python -m venv venv

      - name: Activate venv and install dependencies
        run: |
          source venv/bin/activate || venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          source venv/bin/activate || venv\Scripts\activate
          flake8 drone

      - name: Format check with black
        run: |
          source venv/bin/activate || venv\Scripts\activate
          black --check drone

      - name: Run tests
        run: |
          source venv/bin/activate || venv\Scripts\activate
          pytest -v
